//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TimeEntry
    {
        public long id { get; set; }
        public string UserName { get; set; }
        public Nullable<long> Projectid { get; set; }
        public Nullable<long> Taskid { get; set; }
        public Nullable<decimal> Monday { get; set; }
        public Nullable<decimal> Tuesday { get; set; }
        public Nullable<decimal> Wednesday { get; set; }
        public Nullable<decimal> Thursday { get; set; }
        public Nullable<decimal> Friday { get; set; }
        public Nullable<decimal> Saturday { get; set; }
        public Nullable<decimal> Sunday { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual tbl_Project tbl_Project { get; set; }
        public virtual tbl_task tbl_task { get; set; }
    }
}
